Release 2019.2.1 (#57)
* fix for AttributeError 'x' in numpy.ndarray

Fixes late game error that occurs because cell has no attribute 'x' or 'y', instead, index '0' and '1' are used.

* Refix starter pack assembly

* Exclude select command from CSV renderer's last command

* Bump game engine version to 2019.2.1 for bugfixes

* Add Banana parsing to command parser

* Add Banana parsing to command parser

* Update CommandParser.kt exception message